### PR TITLE
Specification clarifications

### PR DESCRIPTION
**Pull request by jaxoncreed**
Added clarifications for:
 - https://github.com/solid/authentication-panel/issues/87
 - https://github.com/solid/authentication-panel/issues/88
 - https://github.com/solid/authentication-panel/issues/89

### CODE REVIEW

**Review by acoburn — APPROVED** [review]
This is an important clarification 👍 

In the non-normative example, the `sub` claim is also the WebID. Of course the is nothing wrong with this, and an IdP may certainly want to put that value in the `sub` claim, but it's also not something client code should rely on. Should we do anything special with that claim in the example?

**Comment by elf-pavlik** [comment]
OIDC requires sub claim in the id token https://openid.net/specs/openid-connect-core-1_0.html#IDToken

> sub
    REQUIRED. Subject Identifier. A locally unique and never reassigned identifier within the Issuer for the End-User, which is intended to be consumed by the Client, e.g., 24400320 or AItOawmwtWwcT0k51BayewNvutrJUqsvl6qs7A4. It MUST NOT exceed 255 ASCII characters in length. The sub value is a case sensitive string.

We could state that client MUST get WebID from `webid` claim and solid doesn't rely on value of `sub`.

**Review by elf-pavlik — APPROVED** [review]

**Comment by acoburn** [comment]
@jaxoncreed I'd like to get this merged. Can you rebase your branch to address the conflicts? Thanks!

**Review by dmitrizagidulin — APPROVED** [review]
:+1:

**Pull request merged**
