### PR TITLE
Fix typo in primer-login.seqdiag

### LINKED ISSUE #97: Typo in Graphic
There is a typo in the graphic for the Solid OIDC primer.

Screen Shot 2020-11-23 at 16 25 44

### PR DESCRIPTION
**Pull request by TallTed**
fixes #97

### CODE REVIEW

**Review by bblfish — APPROVED** [review]
Oh, interesting that the diagram is encoded in text and can be edited in place.

**Comment by elf-pavlik** [comment]
I think we still need to render image from the diagram, @jaxoncreed are you using https://www.websequencediagrams.com/ ? It seems that exporting SVG and PNG is a premium feature. 

https://mermaid-js.github.io/mermaid/ is open source and it also has online editor https://mermaid-js.github.io/mermaid-live-editor/ i think we could even use mermaid npm module to automate rendering svg from diagram text.

text syntax is almost the same, see [this diagram in mermaid live editor](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG4gIHBhcnRpY2lwYW50IFJQXG4gIHBhcnRpY2lwYW50IEFsaWNlJ3MgT1BcbiAgcGFydGljaXBhbnQgQWxpY2UncyBXZWJJRFxuICBwYXJ0aWNpcGFudCBSUCBXZWJJRFxuICBub3RlIG92ZXIgUlA6IDEuIEFsaWNlIHVzZXMgdGhlIGRlY2VudHBob3RvcyBhcHBcbiAgbm90ZSBvdmVyIFJQOiAyLiBBbGljZSBzZWxlY3RzIGhlciBPUCBvciBXZWJJRFxuICBSUC0-PkFsaWNlJ3MgV2ViSUQ6IDIuMSBSZXRyaWV2ZSBQcm9maWxlXG4gIEFsaWNlJ3MgV2ViSUQtPj5SUDogV2ViSUQgRG9jdW1lbnRcbiAgICBSUC0-PkFsaWNlJ3MgT1A6IDMuIFJldHJpZXZlcyBPUCBjb25maWd1cmF0aW9uXG4gIEFsaWNlJ3MgT1AtPj5SUDogVE9ET1xuICBub3RlIG92ZXIgUlA6IDQuIEdlbmVyYXRlcyBQS0NFIGNvZGUgYW5kIGNvZGUgdmVyaWZpZXJcbiAgbm90ZSBvdmVyIFJQOiA1LiBTYXZlcyBjb2RlIHZlcmlmaWVyIHRvIHNlc3Npb24gc3RvcmFnZVxuICBSUC0-QWxpY2UncyBPUDogNi4gQXV0aG9yaXphdGlvbiBSZXF1ZXN0XG4gIEFsaWNlJ3MgT1AtPlJQIFdlYklEOiA3LiBGZXRjaCBSUCBXZWJJRFxuICBSUCBXZWJJRC0-QWxpY2UncyBPUDogVE9ET1xuICBub3RlIG92ZXIgQWxpY2UncyBPUDogOC4gVmFsaWRhdGVzIHJlZGlyZWN0IHVybCB3aXRoIFdlYklEXG4gIG5vdGUgb3ZlciBBbGljZSdzIE9QOiA5LiBBbGljZSBMb2dzIEluXG4gIG5vdGUgb3ZlciBBbGljZSdzIE9QOiAxMC4gR2VuZXJhdGVzIGEgY29kZVxuICBBbGljZSdzIE9QLT5SUDogMTEuIFNlbmRzIGNvZGUgdG8gcmVkaXJlY3QgdXJsXG4gIG5vdGUgb3ZlciBSUDogMTIuIEdlbmVyYXRlcyBEUG9QIENsaWVudCBLZXkgUGFpclxuICBub3RlIG92ZXIgUlA6IDEzLiBHZW5lcmF0ZXMgYSBEUG9QIEhlYWRlclxuICBSUC0-QWxpY2UncyBPUDogMTQuIFRva2VuIHJlcXVzdCB3aXRoIGNvZGUgYW5kIGNvZGUgdmVyaWZpZXJcbiAgbm90ZSBvdmVyIEFsaWNlJ3MgT1A6IDE1LiBWYWxpZGF0ZXMgY29kZSB2ZXJpZmllclxuICBub3RlIG92ZXIgQWxpY2UncyBPUDogMTYuIFZhbGlkYXRlcyBEUG9QIFRva2VuIHNpZ25hdHVyZVxuICBub3RlIG92ZXIgQWxpY2UncyBPUDogMTcuIENvbnZlcnRzIHRoZSBEUG9QIHB1YmxpYyBrZXkgdG8gYSBKV0sgdGh1bWJwcmludFxuICBub3RlIG92ZXIgQWxpY2UncyBPUDogMTguIEdlbmVyYXRlcyBhY2Nlc3MgdG9rZW5cbiAgbm90ZSBvdmVyIEFsaWNlJ3MgT1A6IDE5LiBHZW5lcmF0ZXMgaWQgdG9rZW5cbiAgbm90ZSBvdmVyIEFsaWNlJ3MgT1A6IDIwLiBHZW5lcmF0ZXMgcmVmcmVzaCB0b2tlblxuICBBbGljZSdzIE9QLT5SUDogMjEuIFNlbmRzIHRva2Vuc1xuIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQiLCJ0aGVtZVZhcmlhYmxlcyI6eyJiYWNrZ3JvdW5kIjoid2hpdGUiLCJwcmltYXJ5Q29sb3IiOiIjRUNFQ0ZGIiwic2Vjb25kYXJ5Q29sb3IiOiIjZmZmZmRlIiwidGVydGlhcnlDb2xvciI6ImhzbCg4MCwgMTAwJSwgOTYuMjc0NTA5ODAzOSUpIiwicHJpbWFyeUJvcmRlckNvbG9yIjoiaHNsKDI0MCwgNjAlLCA4Ni4yNzQ1MDk4MDM5JSkiLCJzZWNvbmRhcnlCb3JkZXJDb2xvciI6ImhzbCg2MCwgNjAlLCA4My41Mjk0MTE3NjQ3JSkiLCJ0ZXJ0aWFyeUJvcmRlckNvbG9yIjoiaHNsKDgwLCA2MCUsIDg2LjI3NDUwOTgwMzklKSIsInByaW1hcnlUZXh0Q29sb3IiOiIjMTMxMzAwIiwic2Vjb25kYXJ5VGV4dENvbG9yIjoiIzAwMDAyMSIsInRlcnRpYXJ5VGV4dENvbG9yIjoicmdiKDkuNTAwMDAwMDAwMSwgOS41MDAwMDAwMDAxLCA5LjUwMDAwMDAwMDEpIiwibGluZUNvbG9yIjoiIzMzMzMzMyIsInRleHRDb2xvciI6IiMzMzMiLCJtYWluQmtnIjoiI0VDRUNGRiIsInNlY29uZEJrZyI6IiNmZmZmZGUiLCJib3JkZXIxIjoiIzkzNzBEQiIsImJvcmRlcjIiOiIjYWFhYTMzIiwiYXJyb3doZWFkQ29sb3IiOiIjMzMzMzMzIiwiZm9udEZhbWlseSI6IlwidHJlYnVjaGV0IG1zXCIsIHZlcmRhbmEsIGFyaWFsIiwiZm9udFNpemUiOiIxNnB4IiwibGFiZWxCYWNrZ3JvdW5kIjoiI2U4ZThlOCIsIm5vZGVCa2ciOiIjRUNFQ0ZGIiwibm9kZUJvcmRlciI6IiM5MzcwREIiLCJjbHVzdGVyQmtnIjoiI2ZmZmZkZSIsImNsdXN0ZXJCb3JkZXIiOiIjYWFhYTMzIiwiZGVmYXVsdExpbmtDb2xvciI6IiMzMzMzMzMiLCJ0aXRsZUNvbG9yIjoiIzMzMyIsImVkZ2VMYWJlbEJhY2tncm91bmQiOiIjZThlOGU4IiwiYWN0b3JCb3JkZXIiOiJoc2woMjU5LjYyNjE2ODIyNDMsIDU5Ljc3NjUzNjMxMjglLCA4Ny45MDE5NjA3ODQzJSkiLCJhY3RvckJrZyI6IiNFQ0VDRkYiLCJhY3RvclRleHRDb2xvciI6ImJsYWNrIiwiYWN0b3JMaW5lQ29sb3IiOiJncmV5Iiwic2lnbmFsQ29sb3IiOiIjMzMzIiwic2lnbmFsVGV4dENvbG9yIjoiIzMzMyIsImxhYmVsQm94QmtnQ29sb3IiOiIjRUNFQ0ZGIiwibGFiZWxCb3hCb3JkZXJDb2xvciI6ImhzbCgyNTkuNjI2MTY4MjI0MywgNTkuNzc2NTM2MzEyOCUsIDg3LjkwMTk2MDc4NDMlKSIsImxhYmVsVGV4dENvbG9yIjoiYmxhY2siLCJsb29wVGV4dENvbG9yIjoiYmxhY2siLCJub3RlQm9yZGVyQ29sb3IiOiIjYWFhYTMzIiwibm90ZUJrZ0NvbG9yIjoiI2ZmZjVhZCIsIm5vdGVUZXh0Q29sb3IiOiJibGFjayIsImFjdGl2YXRpb25Cb3JkZXJDb2xvciI6IiM2NjYiLCJhY3RpdmF0aW9uQmtnQ29sb3IiOiIjZjRmNGY0Iiwic2VxdWVuY2VOdW1iZXJDb2xvciI6IndoaXRlIiwic2VjdGlvbkJrZ0NvbG9yIjoicmdiYSgxMDIsIDEwMiwgMjU1LCAwLjQ5KSIsImFsdFNlY3Rpb25Ca2dDb2xvciI6IndoaXRlIiwic2VjdGlvbkJrZ0NvbG9yMiI6IiNmZmY0MDAiLCJ0YXNrQm9yZGVyQ29sb3IiOiIjNTM0ZmJjIiwidGFza0JrZ0NvbG9yIjoiIzhhOTBkZCIsInRhc2tUZXh0TGlnaHRDb2xvciI6IndoaXRlIiwidGFza1RleHRDb2xvciI6IndoaXRlIiwidGFza1RleHREYXJrQ29sb3IiOiJibGFjayIsInRhc2tUZXh0T3V0c2lkZUNvbG9yIjoiYmxhY2siLCJ0YXNrVGV4dENsaWNrYWJsZUNvbG9yIjoiIzAwMzE2MyIsImFjdGl2ZVRhc2tCb3JkZXJDb2xvciI6IiM1MzRmYmMiLCJhY3RpdmVUYXNrQmtnQ29sb3IiOiIjYmZjN2ZmIiwiZ3JpZENvbG9yIjoibGlnaHRncmV5IiwiZG9uZVRhc2tCa2dDb2xvciI6ImxpZ2h0Z3JleSIsImRvbmVUYXNrQm9yZGVyQ29sb3IiOiJncmV5IiwiY3JpdEJvcmRlckNvbG9yIjoiI2ZmODg4OCIsImNyaXRCa2dDb2xvciI6InJlZCIsInRvZGF5TGluZUNvbG9yIjoicmVkIiwibGFiZWxDb2xvciI6ImJsYWNrIiwiZXJyb3JCa2dDb2xvciI6IiM1NTIyMjIiLCJlcnJvclRleHRDb2xvciI6IiM1NTIyMjIiLCJjbGFzc1RleHQiOiIjMTMxMzAwIiwiZmlsbFR5cGUwIjoiI0VDRUNGRiIsImZpbGxUeXBlMSI6IiNmZmZmZGUiLCJmaWxsVHlwZTIiOiJoc2woMzA0LCAxMDAlLCA5Ni4yNzQ1MDk4MDM5JSkiLCJmaWxsVHlwZTMiOiJoc2woMTI0LCAxMDAlLCA5My41Mjk0MTE3NjQ3JSkiLCJmaWxsVHlwZTQiOiJoc2woMTc2LCAxMDAlLCA5Ni4yNzQ1MDk4MDM5JSkiLCJmaWxsVHlwZTUiOiJoc2woLTQsIDEwMCUsIDkzLjUyOTQxMTc2NDclKSIsImZpbGxUeXBlNiI6ImhzbCg4LCAxMDAlLCA5Ni4yNzQ1MDk4MDM5JSkiLCJmaWxsVHlwZTciOiJoc2woMTg4LCAxMDAlLCA5My41Mjk0MTE3NjQ3JSkifX0sInVwZGF0ZUVkaXRvciI6ZmFsc2V9) 

it renders like this (TODO comes from label being required, I didn't change some arrows from `->` to `-->` so that they have pointed end)

image

**Comment by TallTed** [comment]
@elf-pavlik -- I have no argument with your change, but I think it should be in its own PR or issue, as this one just fixes a couple of tiny typos.

**Comment by elf-pavlik** [comment]
I agree, but we should leave #97 open since this PR on it's own will not update the image.

**Review by elf-pavlik — APPROVED** [review]

**Comment by TallTed** [comment]
@elf-pavlik -- SVG image is now updated. I hadn't realized there was an `svg` as well as the `seqdiag`.  This PR does now fix #97 -- but it doesn't do anything like your suggested flow revision.

**Pull request merged**
