### PR TITLE
clarify meetings

### PR DESCRIPTION
**Pull request by elf-pavlik**
This PR aims to communicate the current practice. We can create new issue if we want to adjust how we organize meetings and based on outcomes create new PR to update it again.

### CODE REVIEW

**Review by acoburn — APPROVED** [review]

**Comment by TallTed** [comment]
If we cannot use the W3 Calendar via the Solid CG, nor any other subscribable calendar, I request that meeting notices (preferably in/with .ics), agendae, and minutes be published to the mailing list, in addition to the Gitter channel.  If this is not immediately implementable, it is not necessary for this PR, and could be shifted to its own issue.

**Comment by acoburn** [comment]
This change _does_ bring the panel in line with the W3C calendar. Previously, being tied to US Eastern Time in the README, meant that the meeting times were aligned with the W3C calendar during only part of the year.

**Comment by csarven** [comment]
But Ted, I've acknowledged that we are trying to get to updating the W3C calendar in https://github.com/solid/authorization-panel/issues/325#issuecomment-1284036560 . The only concern may be that, well, how does one indicate "sporadically" in a calendar :) If people want to reserve the slot in the calendar, we can of course do that and indicate "sporadically" so that people don't show up and not find others or have no agenda and so on. Until there is something concrete and committed, I don't think we need to add it to the W3C calendar. This is not intended to be a barrier in any way but to minimise any confusion.

**Comment by TallTed** [comment]
> [@acoburn] This change does bring the panel in line with the W3C calendar. Previously, being tied to US Eastern Time in the README, meant that the meeting times were aligned with the W3C calendar during only part of the year.

My request was not at all about timezones, nor Daylight Saving vs Standard time.  (Note that "US Eastern Time" a/k/a "ET" always matches the local clock, whether that local clock is in "EST" a/k/a "Eastern Standard Time" or "EDT" a/k/a "Eastern Daylight Saving Time", and that the W3 timezone has historically been ET, since all the tools [primarily IRC and bots such as zakim, agendabot, github-bot, etc.] are located in Cambridge, MA, USA.)

My request is that all Solid panel meetings be added to the [Solid CG calendar](https://www.w3.org/groups/cg/solid/calendar), which is served by the W3C calendar.

I note that the W3 calendar may be displayed in any timezone. (See the inline menu, at upper left of the [calendar display, here in UTC](https://www.w3.org/groups/cg/solid/calendar?tz=UTC&tf=1&past=), which defaults to "Per event time zone")


> [@csarven] The only concern may be that, well, how does one indicate "sporadically" in a calendar

I'm a member of a number of groups that have a weekly or biweekly timeslot booked as "tentative" until it gets "confirmed" or "canceled", and which cancel the call more often than not.  This works perfectly well, and does not require anyone to monitor a chat 24/7, as opposed to automatically receiving calendar updates or even occasionally checking a mailing list.

**Comment by elf-pavlik** [comment]
> This works perfectly well, and does not require anyone to monitor a chat 24/7, as opposed to automatically receiving calendar updates or even occasionally checking a mailing list.

I people can check if meeting was announced whenever they want to know if it will be happening next Monday. They can even just check hours before meeting to make sure it wasn't called last minute.

@csarven who has write access to [Solid CG calendar](https://www.w3.org/groups/cg/solid/calendar) ? How easily meetings can be added there as they get scheduled?

**Comment by elf-pavlik** [comment]
I'm going to merge this PR, we should create a dedicated issue here or in specification repo to clarify how [Solid CG calendar](https://www.w3.org/groups/cg/solid/calendar) for announcing planned meetings.

**Pull request merged**
